### ISSUE TITLE
Unable to install in Umbraco 7.1.4

### ISSUE THREAD

**Issue by kieranjohn** [uComponents/uComponents#25]
Could not load types from assembly uComponents.DataTypes

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Reflection.ReflectionTypeLoadException: Could not load types from assembly uComponents.DataTypes, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null, errors:
Exception: System.TypeLoadException: Could not load type 'umbraco.editorControls.mediapicker.MemberPickerDataType' from assembly 'umbraco.editorControls, Version=1.0.5261.28135, Culture=neutral, PublicKeyToken=null'.

**Comment by leekelleher** [comment]
This has been fixed in the v6.1.0 release.

**Comment by Korayem** [comment]
Any ETA to support v7.x?

**Comment by leekelleher** [comment]
@Korayem How do you mean with v7 support?

uComponents v6.1.0 package will install without error in Umbraco v7.x back-office. In terms of data-types - no, it's not happening - there are many great alternatives, (see comments above).

**Comment by Korayem** [comment]
@leekelleher excellent! Indeed, Archetype and nuPicks seem to cover it for me.

You could also update the project description on Our Umbraco and Github readme.md for noobs like me to know it doesn't support v7.x
