### ISSUE TITLE
Use Examine or Cache instead of DB

### ISSUE THREAD

**Issue by xzaz** [uComponents/uComponents#34]
We use multiple multiple-node--tree-pickers in our website. There are around 16000+ nodes divided in 2000 / tree. While loading the tree trough a MNTP it takes up around 2 minutes to load the nodes. Is it possible to load the data with the help of Examine / cache?

**Comment by leekelleher** [comment]
Hi @xzaz 

MNTP was moved over to the Umbraco core in v4.8.0, and marked as legacy code within uComponents, so any new features would need to be requested on the [Umbraco issue tracker](issues.umbraco.org/issues/U4).

However Umbraco v6.x has been frozen, so they wont be accepting any new feature requests.

If you are using Umbraco v7.x, then you can look at the [nuPickers](https://github.com/uComponents/nuPickers) package, which does have support for [Lucene/Examine based pickers](https://github.com/uComponents/nuPickers/wiki/Data-Source-Lucene).

If you are stuck with an earlier version of Umbraco and uComponents, please do feel free to make any customisations to the source-code.

Thanks, Lee
