### ISSUE TITLE
What happend with Helper.Xml.CouldItBeXml() method in v.5.5.4?

### ISSUE THREAD

**Issue by rekosko** [uComponents/uComponents#35]
Hello,

I've got problems after updating uComponents from version 5.0.0 to 5.5.4.

It seems that method mentioned in this post title is missing? What happend? Is there any replacement for it?

**Comment by leekelleher** [comment]
Hi @rekosko 

The `Helper.Xml.CouldItBeXml` helper method is still there.

https://github.com/uComponents/uComponents/blob/master/src/uComponents.Core/Helper-Xml.cs

But as far as I can recall, it's always been marked as an internal helper.
