### ISSUE TITLE
URL Picker redux: "ReferenceError: Can't find variable: responseText"

### ISSUE THREAD

**Issue by bewildergeist** [uComponents/uComponents#37]
Hot off the heels of #30 and the fix in #33, I'm afraid:

On an Umbraco 6.1.6 running uComponents 6.1.0, if I upload a media item to a URL Picker i get the following console error:

     ReferenceError: Can't find variable: responseText

Which stands to reason, as `responseText` should've been `response` here:

https://github.com/uComponents/uComponents/commit/1f43ea7956bafd5f2feda4f1bb62846b406227b3#diff-19409589b2756608c2502d43d4a0d30bR380

Do you want a PR for that? :)

**Comment by leekelleher** [comment]
@bewildergeist Thanks for spotting this! (I'm pretty sure I'd tested it, but guess not :disappointed:) If you have time for a PR, that would be most appreciated, thanks!

**Comment by leekelleher** [comment]
@bewildergeist No worries about a PR, I've added the fix on the "dev-6.x" branch.  I'll look to get a v6.1.1 release out next week, (I also found out that there is another issue with DLL version numbers, which I should find too).

**Comment by leekelleher** [comment]
Fixed, due for release in v6.1.1

**Comment by bewildergeist** [comment]
Excellent! We have a customer who'll be happy to get a 6.1.1 deployed to their solution, so thanks for the quick turnaround!
