### ISSUE TITLE
SSL websites does not work with NotFoundHandlers

### ISSUE THREAD

**Issue by runegronkjaer** [uComponents/uComponents#39]
The code checks the SERVER_PORT a couple of places and only approve port 80 as a normal port. It should check for the default ssl port 443 as well.

**Comment by leekelleher** [comment]
@runegronkjaer Thanks for raising this, it's much appreciated!

To be completely honest, uComponents is no longer high on my priorities, so I doubt that I'll get around to fixing this issue.  If you would like to submit a patch for it, that would be great.

**Comment by runegronkjaer** [comment]
I would love to, but it seems like I can't push a new branch to make the pull request. As I read it here: https://help.github.com/articles/creating-a-pull-request/
that's what I need to do. I get a permission denied, when trying to push my changes.
Never made an actual pull request before.

**Comment by leekelleher** [comment]
@runegronkjaer Just checking, have you made a fork of the repo first?

**Comment by leekelleher** [comment]
@runegronkjaer I also meant to say, no worries - it's all a learning curve. I'm happy to help advise.

We don't have a CONTRIBUTING file on uComponents, but here's one from Ditto - it has guidelines on how to do a fork and send a pull-request.

https://github.com/leekelleher/umbraco-ditto/blob/develop/CONTRIBUTING.md#pull-requests

**Comment by runegronkjaer** [comment]
I think I got it now:
https://github.com/uComponents/uComponents/pull/40

**Comment by leekelleher** [comment]
Cool, thanks @runegronkjaer - I'll close this one and review your pull-request! :+1:
