### ISSUE TITLE
Please deprecate this project

### ISSUE THREAD

**Issue by alirobe** [uComponents/uComponents#42]
The website and package info should mark this project as deprecated, as it no longer supports the latest versions of Umbraco.

**Comment by leekelleher** [comment]
@alirobe Thanks for raising this.  The project isn't deprecated, it is still widely used on Umbraco v4.5 to v6.x installs, (as stated in this repo's README).  Albeit it is no longer being actively developed, but if any urgent bugs or security issues come will, we'll endeavour to support it).

I do appreciate that uComponents may be confused for supporting Umbraco v7.x+.  We're open to advice and specific suggestions on how this could be less confusing.

**Comment by alirobe** [comment]
@leekelleher that is literally **the definition** of a deprecated project. Supported for old environments, but not intended for new projects.
